### PR TITLE
Adding mixed and pyramid meshes

### PR DESCRIPTION
**Pull request by mlstowell**

### CODE REVIEW

**Review by tzanio — APPROVED** [review]

**Comment by wnissen** [comment]
@tzanio Does this mean we could produce a mixed mesh with quads in the important parts and tris in the air?

**Comment by tzanio** [comment]
Oh, we've been supporting the 2D case for a long time, see e.g. `mfem/data/star-mixed.mesh`.

This is for the 3D case, which now supports 1st order pyramids, including the case of mixed meshes with hex/tex/prism/pyramid elements.

**Comment by wnissen** [comment]
Suh-weet!

**Comment by koning** [comment]
Great news, I will try this out with the MFEM hypre interface.

**Comment by tzanio** [comment]
@koning, see https://github.com/mfem/mfem/pull/2400

**Pull request merged**
